// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © jawauntb

//@version=5
strategy("Stochastic and CMF Strategy", overlay=true)

// Stochastic Indicator
periodK = input.int(20, " %K Length", minval=1)
smoothK = input.int(1, "%K Smoothing", minval=1)
periodD = input.int(3, "%D Smoothing", minval=1)
k = ta.sma(ta.stoch(close, high, low, periodK), smoothK)
d = ta.sma(k, periodD)

// Chaikin Money Flow Indicator
length = input.int(10, "Length", minval=1)
ad = close == high and close == low or high == low ? 0 : ((2 * close - low - high) / (high - low)) * volume

sumAd = 0.0
sumVolume = 0.0
for i = 0 to length - 1
    sumAd := sumAd + ad[i]
    sumVolume := sumVolume + volume[i]

mf = sumAd / sumVolume

// Define conditions for entering a long or short position
enterLong = ta.crossover(k, d) and mf > 0.1
enterShort = ta.crossunder(k, d) and mf < 0.08

// Define conditions for exiting a position
exitLong = ta.crossunder(k, d) and mf < -0.1
exitShort = ta.crossover(k, d) and mf > 0.06

// Execute trades based on the conditions
strategy.entry("Long", strategy.long, when=enterLong)
strategy.close("Long", when=exitLong)
strategy.entry("Short", strategy.short, when=enterShort)
strategy.close("Short", when=exitShort)

